// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Time from "@dannyfritz/flock/time";

let _t = new Time.Timer(10);

console.log(_t);

console.log(_t.duration);

console.log(_t.tick(9));

console.log(_t.duration);

console.log(_t);

export {
  _t,
}
/* _t Not a pure module */
