name: CD

on:
  push:
    branches:
    - master
    - dev

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Setup Token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install
      - name: Debug
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Publish Beta
        run: yarn workspace flock-ecs publish --tag beta
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      - name: Publish Stable
        run: yarn workspace flock-ecs publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
