name: CI

on:
  push:
    branches: 
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v1
      - name: Install Yarn and Dependencies
        uses: borales/actions-yarn@v2.0.0
      - name: Test
        run: yarn test
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v1
      - name: Install Yarn and Dependencies
        uses: borales/actions-yarn@v2.0.0
      - name: Lint
        run: yarn lint
