name: CI

on:
  pull_request:
    branches:
    - master
    - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
      - run: ls -r
      - name: Test
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
      - name: Lint
        run: yarn lint
